name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch: # Add this line to enable manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        npm install

    - name: Build React app
      run: |
        npm run build

    - name: Create .ssh directory
      run: |
        mkdir -p ~/.ssh

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add host to known_hosts
      run: |
        ssh-keyscan ssh.mertalukas.cz >> ~/.ssh/known_hosts

    - name: Deploy
      run: ssh root@mertalukas "cd /var/www/html/public/main && git pull && ./deploy.sh"